# Generated by Django 3.1.2 on 2021-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211003_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservice',
            name='price',
            field=models.FloatField(),
        ),
    ]
